### ISSUE TITLE
Consider other dispersion indexes for nominal variables

### ISSUE THREAD

**Issue by krajcsi** [cogstat/cogstat#130]
See a comprehensive list of indexes at https://en.wikipedia.org/wiki/Qualitative_variation

**Comment by Majalebenicnik** [comment]
The concept of variability of a nominal dispersion is different than in the case of interval variables. The minimum value of an index is obtained only when all data fall into a single category, whereas the maximum value is reached when an identical number of data fall into each category. Indices of nominal variability are, therefore, a measure of the similarity of frequencies in different categories. Alternative indices work similarly in this sense and even if they measure this concept differently. Because the overall concept is the same, and the provided differences do not seem to be often stressed features, the current solution alone may be appropriate for CogStat.
