### ISSUE TITLE
What power should be used for power analysis?

### ISSUE THREAD

**Issue by krajcsi** [cogstat/cogstat#243]
CogStat currently uses 95%. However, the most common value may be 80%. It is not clear what value should be optimal. See, for example, Giner-Sorolla et al. 2023 https://psyarxiv.com/rv3kw

Also, see Brysbaert, 2019 https://doi.org/10.5334/joc.72 for examples about what can be realistic.

**Comment by Majalebenicnik** [comment]
Since Cohen’s (1962) seminal study, which revealed very low overall power to detect small and medium effect sizes, he strongly advocated for higher-powered studies. Cohen (1965, 1988) proposed a conventional value of .80, with the rationale that type I error is four times more damaging than type II error. The proposed value was given with the hope that it will be ignored if the required sample size exceeds the researchers’ resources or if an alternative justification for the power value is provided (Cohen, 1965, 1988). Today, the use of .80 is widespread despite its inadequate justification (Lakens, 2022). Since the proposed convention, authors have stressed the equal, in some cases even greater, importance of type II error (Fiedler et. al, 2012) and emphasized the damaging consequences of low-powered studies (Button et. al, 2013a). Increasing power demands a larger sample size but results in lower type two error rates, greater precision of effect size estimates (Button et. al, 2013b), aids in the field-wide dissemination of false positives (Giner-Sorolla et. al., 2023), and increases the overall informational value of a study (Lakens, 2022). 

Unless additional justifications are given, the default power value should be set to 95% due to the equal importance of the two errors and the above-mentioned advantages. However, CogStat should report observable effect sizes for both the commonly used 80% and a higher 95% power since the increase in sample size (using 95% power) might be too expensive and sometimes unfeasible. Reporting 80% also enables result comparison with previous studies. 

Button, K. S., Ioannidis, J. P., Mokrysz, C., Nosek, B. A., Flint, J., Robinson, E. S., & Munafò, M. R. (2013a). Power failure: why small sample size undermines the reliability of neuroscience. Nature reviews. Neuroscience, 14(5), 365–376. https://doi.org/10.1038/nrn3475

Button, K. S., Ioannidis, J. P., Mokrysz, C., Nosek, B. A., Flint, J., Robinson, E. S., & Munafò, M. R. (2013b). Confidence and precision increase with high statistical power. Nature reviews. Neuroscience, 14(8), 585–586. https://doi.org/10.1038/nrn3475-c4

Cohen, J. (1962). The statistical power of abnormal-social psychological research: a review. The Journal of Abnormal and Social Psychology, 65(3), 145.

Cohen. J. (1965). Some statistical issues in psychological research. In B. B. Wolman (Ed.). Handbook of clinical psychology (pp. 95-121). New York: McGraw-Hill.

Cohen, J. (1988). Statistical Power Analysis for the Behavioral Sciences (2nd ed.). Routledge. https://doi.org/10.4324/9780203771587 

Fiedler, K., Kutzner, F., & Krueger, J. I. (2012). The long way from α-error control to validity proper: Problems with a short-sighted false-positive debate. Perspectives on Psychological Science, 7(6), 661-669.

Giner-Sorolla, R., Montoya, A. K., Aberson, C., Carpenter, T., Lewis, N. A., Jr., Bostyn, D. H., … Soderberg, C. K. (2023). Power to Detect What? Considerations for Planning and Evaluating Sample Size. https://doi.org/10.31234/osf.io/rv3kw 

Lakens, D. (2022). Sample Size Justification. Collabra: Psychology, 8(1).[ https://doi.org/10.1525/collabra.33267](https://doi.org/10.1525/collabra.33267)

**Comment by krajcsi** [comment]
Thanks, Maja! Based on that, we keep on using the 95% as a recommended/ideal value, and add 80% to be comparable with other studies.
