### ISSUE TITLE
How to calculate variation ratio when there are several modes?

### ISSUE THREAD

**Issue by krajcsi** [cogstat/cogstat#268]
Currently, only a single mode is considered, independent of how many modes are observed.

See also #130

**Comment by Majalebenicnik** [comment]
Although we couldn’t find descriptions that consider the possible presence of two or more modes, the present solution (i.e., using only the frequency of a single category, even when there are several modes) is preferred since it accurately reflects the variation. Consider the example where all categories have the same frequency. Using multiple modes, VR would equal 0. This could be interpreted as a highly homogeneous sample, when, in fact, frequencies are evenly distributed across all categories. Because variation ratio is primarily a measure of dispersion, using it with a single mode even when there are several modes accurately reflects spread.

**Comment by krajcsi** [comment]
Thanks, @Majalebenicnik, it is a reasonable argument. I close the issue.
