### ISSUE TITLE
Copy functions of results

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#41]
When selecting a result/output (right-click on it) the selection "Copy" is faded and "Select all" vanishes when you go over with the cursor.

Example: 

![bug4](https://cloud.githubusercontent.com/assets/22355317/22331490/02a18e94-e3cc-11e6-875b-5c5260eef33f.jpg)

<i>CogStat Version from 30.11.16</i>
<i>System: Windows 10</i>

**Comment by RRP89** [comment]
Update: "Select all" doesn't vanish anymore with the latest update from 13.12.16. 

Copy is still faded.

**Comment by krajcsi** [comment]
1. Select all was fixed in this commit: https://github.com/cogstat/cogstat/commit/8254ba39604b4c9eb81f44af7f2c07fc8844637c

2. Copy is only available when part of the output is selected, so in a strict sense it works correctly. On the other hand, it is not intuitive that an image should be selected first. So right clock on an image also should select it, to make the Copy command available.

**Comment by krajcsi** [comment]
After checking a few other packages, I saw that it is quite common that right clicking on an image does not make it copyable - although there are counter examples too. Because both solutions seem to be acceptable, I close this issue. If there are additional considerations, feel free to reopen this issue and add further points why copy without selection should work.
